const { inherits } = require('util');

module.exports = {
  enabled: true,
  content: ['./src/**/*.html', './src/**/*.ts'],
  darkMode: 'class', // Enable dark mode, use class="dark" in html
  theme: {
    extend: {
      colors: {
        background: 'var(--background)',
        foreground: 'var(--foreground)',
        muted: 'var(--muted)',
        'muted-foreground': 'var(--muted-foreground)',
        primary: 'var(--primary)',
        'primary-foreground': 'var(--primary-foreground)',
        secondary: 'var(--secondary)',
        'secondary-foreground': 'var(--secondary-foreground)',
        accent: 'var(--accent)',
        'accent-foreground': 'var(--accent-foreground)',
        destructive: 'var(--destructive)',
        'destructive-foreground': 'var(--destructive-foreground)',
        code: 'var(--code)',
        'code-foreground': 'var(--code-foreground)',
      },
      typography: ({ theme }) => ({
        DEFAULT: {
          css: {
            '--tw-prose-body': theme('colors.foreground'),
            '--tw-prose-headings': theme('colors.foreground'),
            '--tw-prose-lead': theme('colors.foreground'),
            '--tw-prose-links': theme('colors.foreground'),
            '--tw-prose-bold': theme('colors.foreground'),
            '--tw-prose-counters': theme('colors.foreground'),
            '--tw-prose-bullets': theme('colors.foreground'),
            '--tw-prose-hr': theme('colors.foreground'),
            '--tw-prose-quotes': theme('colors.foreground'),
            '--tw-prose-quote-borders': theme('colors.foreground'),
            '--tw-prose-captions': theme('colors.foreground'),
            '--tw-prose-kbd': theme('colors.foreground'),
            '--tw-prose-kbd-shadows': theme('colors.foreground'),
            '--tw-prose-code': theme('colors.background'),
            '--tw-prose-pre-code': theme('colors.background'),
            '--tw-prose-pre-bg': theme('colors.muted-foreground'),
            '--tw-prose-th-borders': theme('colors.foreground'),
            '--tw-prose-td-borders': theme('colors.foreground'),
            /* the rest seems to not be needed, since we are using our own dark-mode solution */
            '--tw-prose-invert-body': null,
            '--tw-prose-invert-headings': null,
            '--tw-prose-invert-lead': null,
            '--tw-prose-invert-links': null,
            '--tw-prose-invert-bold': null,
            '--tw-prose-invert-counters': null,
            '--tw-prose-invert-bullets': null,
            '--tw-prose-invert-hr': null,
            '--tw-prose-invert-quotes': null,
            '--tw-prose-invert-quote-borders': null,
            '--tw-prose-invert-captions': null,
            '--tw-prose-invert-kbd': null,
            '--tw-prose-invert-kbd-shadows': null,
            '--tw-prose-invert-code': null,
            '--tw-prose-invert-pre-code': null,
            '--tw-prose-invert-pre-bg': null,
            '--tw-prose-invert-th-borders': null,
            '--tw-prose-invert-td-borders': null,
          },
        },
      }),
    },
  },
  variants: {
    extend: {},
  },
  plugins: [require('@tailwindcss/typography')],
};
